In [41]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [39]:
!pip install numpy
import numpy as np
my_list=(10, 3, 4)
x=np.array([10, 3, 4])
x


[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip


array([10,  3,  4])

In [2]:
from numpy import random 
arr=random.uniform(-3, 3, size = (3, 4))
arr

array([[ 2.3567622 , -0.29504595, -2.4576147 , -2.06470084],
       [ 2.15180022,  2.61421194,  2.48875615, -2.05448647],
       [ 1.99616727,  0.14595542,  0.94398974, -2.2196239 ]])

In [3]:
type(arr)

numpy.ndarray

In [4]:
xarr=np.array([[2, 5, 8], [7, 3, 6]])
xarr

array([[2, 5, 8],
       [7, 3, 6]])

In [5]:
xarr=np.array([[3, 7, 9, 3], [4, 3, 2, 2]])
xarr

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

In [6]:
x=np.random.rand(20) #tek boyutlu olduğu için 20 yazdık
x

array([2.85622903e-01, 2.42425715e-01, 5.57308080e-01, 3.18068983e-01,
       6.92867370e-01, 8.69747277e-04, 9.88428650e-01, 7.66573857e-01,
       6.42379925e-01, 6.82793348e-01, 4.33578798e-01, 7.31225093e-01,
       1.86940587e-01, 1.05308989e-01, 3.36346696e-01, 1.87403957e-01,
       4.17487260e-01, 1.90332617e-02, 7.55744884e-01, 6.38622000e-01])

In [7]:
x=np.random.rand(3, 3)
x

array([[0.14476006, 0.75457334, 0.8366793 ],
       [0.9794857 , 0.06453636, 0.70858289],
       [0.3912752 , 0.62957097, 0.3777151 ]])

In [8]:
x=np.random.randint(15, 16)
x

15

In [9]:
x=np.random.randint(1, 100, 15)
x

array([91,  4, 82, 57,  8, 79,  1, 30, 56,  3, 96, 14, 20, 45, 80])

In [10]:
x=np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
x=np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [12]:
x=np.ones((7, 7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [13]:
x=np.zeros((8))
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
x=int(input("Give me an integer="))
y=random.randint(0, x, (3, 10))
y

Give me an integer=5


array([[4, 2, 2, 0, 2, 0, 0, 1, 0, 3],
       [2, 2, 2, 1, 4, 0, 3, 4, 3, 2],
       [2, 2, 3, 2, 1, 0, 3, 4, 4, 0]])

In [15]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x=np.array([2, 4, 6, 8])
y=np.array([10, 12, 14, 16, 18])
z=np.concatenate((x,y))
z

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
x = x**2
x

array([ 4, 16, 36, 64])

In [18]:
xx=np.square(x)
xx

array([  16,  256, 1296, 4096])

In [19]:
y=np.sqrt(x)
y

array([2., 4., 6., 8.])

In [20]:
x=np.arange(1, 10)
y=np.exp(x)
y

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [21]:
x=([5, 7, 20])
y=([9, 15, 4])
z=np.sqrt(np.absolute(np.square(x)-np.square(y)))
z

array([ 7.48331477, 13.26649916, 19.59591794])

In [22]:
x = np.array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [23]:
x[0]

3

In [24]:
x[:3]

array([3, 5, 6])

In [25]:
x[:3] = 7
x

array([ 7,  7,  7,  2,  8, 10, 20, 50])

In [26]:
y = np.array([[6, 9, 7, 1],
       [6, 5, 5, 5],
       [6, 9, 1, 8],
       [8, 9, 3, 1]])
y

array([[6, 9, 7, 1],
       [6, 5, 5, 5],
       [6, 9, 1, 8],
       [8, 9, 3, 1]])

In [27]:
y[0]

array([6, 9, 7, 1])

In [28]:
y[0][0]

6

In [29]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X[4][:5] = 0
#np.zeros(5)
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [30]:
x = np.array([[4, 4, 3, 9, 6],
       [9, 9, 8, 9, 2],
       [4, 2, 1, 3, 3],
       [8, 1, 1, 6, 3],
       [1, 3, 6, 8, 8]])
x

array([[4, 4, 3, 9, 6],
       [9, 9, 8, 9, 2],
       [4, 2, 1, 3, 3],
       [8, 1, 1, 6, 3],
       [1, 3, 6, 8, 8]])

In [31]:
y = x[x>=8]
y

array([9, 9, 9, 8, 9, 8, 8, 8])

In [32]:
y = x[x%2==1]
y

array([3, 9, 9, 9, 9, 1, 3, 3, 1, 1, 3, 1, 3])

In [33]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [34]:
#MINI CHALLENGE #5: In the following matrix, replace negative elements by 0 and replace odd elements with -2
X[X < 0] =0
X[X%2==1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

In [35]:
my_dict= { "Bank client ID": [111, 222, 333, 444],
          "Bank Client Name": ["Chanel", "Steve", "Mitch", "Ryan"],
          "Net worth[$]": [3500, 29000, 10000, 2000]


[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
